QWEN_API_KEY = ""
QWEN_CHAT_MODEL_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
QWEN_EMBEDDING_MODEL = "text-embedding-v4"
QWEN_CHAT_MODEL = "qwen-plus"
QWEN_RERANKER_MODEL = "qwen3-rerank"

MILVUS_URL = "http://192.168.48.131:19530"
MILVUS_USER = "root"
MILVUS_PASSWORD = "Milvus"

MYSQL_HOST = "192.168.48.131"
MYSQL_PORT = 3306
MYSQL_USER = "root"
MYSQL_PASS = "123456"
MYSQL_DATABASE = "ai_web"
MYSQL_CHATSET = "utf8mb4"
MYSQL_MESSAGE_TABLE = "chat_message"
MYSQL_SESSION_TABLE = "session"

POSTGRESQL_HOST = "192.168.48.131"
POSTGRESQL_PORT = 5432
POSTGRESQL_USER = "root"
POSTGRESQL_PASS = "123456"
POSTGRESQL_DATABASE = "ai_web"
