API_KEY = ""
QWEN_CHAT_MODEL_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
QWEN_EMBEDDING_MODEL = "text-embedding-v4"

MILVUS_URL = ""
USER = ""
PASSWORD = ""


MYSQL_HOST = ""
MYSQL_PORT = 3306
MYSQL_USER = ""
MYSQL_PASS = ""
MYSQL_DATABASE = ""
MYSQL_CHATSET = ""
MYSQL_MESSAGE_TABLE = ""
MYSQL_SESSION_TABLE = ""

POSTGRESQL_HOST = ""
POSTGRESQL_PORT = 5432
POSTGRESQL_USER = ""
POSTGRESQL_PASS = ""
POSTGRESQL_DATABASE = ""